version: "3.4"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=8bfw,jvvd
    volumes:
      - /var/opt/mssql